### ISSUE TITLE
Problems to using napalm-exos driver

### ISSUE THREAD

**Issue by dandel789** [ixaustralia/napalm-exos#7]
Hi!

I just starting to analize the possibilities to use napalm within my network. I am testing with this driver.. but it is something wrong.. can anyone help me? 

Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
**>>> get_network_driver('exos')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/napalm/base/__init__.py", line 99, in get_network_driver
    install_name=name
napalm.base.exceptions.ModuleImportError: Cannot import "exos". Is the library installed?**
>>> get_network_driver('ios')
<class 'napalm.ios.ios.IOSDriver'>
>>> get_network_driver('junos')
<class 'napalm.junos.junos.JunOSDriver'>

I cloned this project ann intall it.

Thanks in advance!

**Comment by astruwe** [comment]
Hello @dandel789 ,

please try the following:

`pip3 install git+https://github.com/ixaustralia/napalm-exos.git`

I think this has helped.
